[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]] 
threshold = 30
style = "bold yellow"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# when capacity is over 30%, the battery indicator will not be displayed

[directory]
truncation_length = 20
truncation_symbol = "…/"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
